import fetch from 'node-fetch';
import { execSync } from 'child_process';
import { readConfig } from './config.js';

/**
 * ADO REST API client for posting PR comments.
 * Uses `az cli` to fetch a Bearer token (no PAT needed).
 * 
 * Uses config.json for default ADO org/project, with environment variables
 * available as optional overrides:
 *   ADO_ORG        - Organization name (e.g., "msazure")
 *   ADO_PROJECT    - Project name (e.g., "One")
 * 
 * Requires `az login` to have been run beforehand.
 */

let cachedToken = null;
let tokenExpiry = 0;

async function getAccessToken() {
  if (cachedToken && Date.now() < tokenExpiry) return cachedToken;

  const result = execSync(
    'az account get-access-token --resource 499b84ac-1321-427f-aa17-267ca6975798 --query "{token:accessToken,expires:expiresOn}" -o json',
    { encoding: 'utf-8' }
  );
  const parsed = JSON.parse(result);
  cachedToken = parsed.token;
  // Expire 2 minutes early to avoid edge cases
  tokenExpiry = new Date(parsed.expires).getTime() - 120_000;
  return cachedToken;
}

async function getConfig() {
  const config = await readConfig();
  const org = process.env.ADO_ORG || config.ado?.org;
  const project = process.env.ADO_PROJECT || config.ado?.project;
  if (!org || !project) {
    const err = new Error('Missing ADO org/project. Set config.ado.org and config.ado.project or use ADO_ORG / ADO_PROJECT.');
    err.statusCode = 400;
    throw err;
  }
  return { org, project };
}

async function authHeader() {
  const token = await getAccessToken();
  return `Bearer ${token}`;
}

function apiBase(org, project) {
  return `https://dev.azure.com/${org}/${project}/_apis`;
}

function buildCommentFooter() {
  return '\n\n---\n<sub>Generated by PR Review Agent. Curated by Nathan - this comment was reviewed before posting. Replies to this comment will help improve it.</sub>';
}

/**
 * Post a comment thread to a pull request.
 * Creates an inline comment at the specified file and line range.
 */
export async function postPRComment(repoName, prId, { file, startLine, endLine, comment, suggestion }) {
  const { org, project } = await getConfig();
  const base = apiBase(org, project);
  const url = `${base}/git/repositories/${repoName}/pullRequests/${prId}/threads?api-version=7.1`;

  // Build the comment body with suggestion if present
  let body = comment;
  if (suggestion) {
    body += `\n\n**Suggestion:**\n${suggestion}`;
  }
  body += buildCommentFooter();

  const threadPayload = {
    comments: [
      {
        parentCommentId: 0,
        content: body,
        commentType: 1, // text
      }
    ],
    status: 1, // Active
  };

  // Add file/line context for inline comments
  if (file) {
    threadPayload.threadContext = {
      filePath: file.startsWith('/') ? file : `/${file}`,
      rightFileStart: { line: startLine || 1, offset: 1 },
      rightFileEnd: { line: endLine || startLine || 1, offset: 1 },
    };
  }

  const response = await fetch(url, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      'Authorization': await authHeader(),
    },
    body: JSON.stringify(threadPayload),
  });

  if (!response.ok) {
    const errorText = await response.text();
    const err = new Error(parseAdoError(response.status, errorText));
    err.statusCode = response.status;
    throw err;
  }

  const result = await response.json();
  return {
    threadId: result.id,
    url: `https://dev.azure.com/${org}/${project}/_git/${repoName}/pullrequest/${prId}`,
  };
}

/**
 * Get PR details from ADO (used for metadata enrichment).
 */
export async function getPRDetails(repoName, prId) {
  const { org, project } = await getConfig();
  const base = apiBase(org, project);
  const url = `${base}/git/repositories/${repoName}/pullRequests/${prId}?api-version=7.1`;

  const response = await fetch(url, {
    headers: { 'Authorization': await authHeader() },
  });

  if (!response.ok) {
    const errorText = await response.text();
    const err = new Error(parseAdoError(response.status, errorText));
    err.statusCode = response.status;
    throw err;
  }

  return response.json();
}

export async function getPRThreadComments(repoName, prId, threadId) {
  const { org, project } = await getConfig();
  const base = apiBase(org, project);
  const url = `${base}/git/repositories/${repoName}/pullRequests/${prId}/threads/${threadId}/comments?api-version=7.1`;

  const response = await fetch(url, {
    headers: { 'Authorization': await authHeader() },
  });

  if (!response.ok) {
    const errorText = await response.text();
    const err = new Error(parseAdoError(response.status, errorText));
    err.statusCode = response.status;
    throw err;
  }

  const result = await response.json();
  return result.value || [];
}

/** Extract a readable message from ADO error responses */
function parseAdoError(status, body) {
  try {
    const parsed = JSON.parse(body);
    return parsed.message || `ADO API error ${status}`;
  } catch {
    return `ADO API error ${status}: ${body}`;
  }
}
